### ISSUE TITLE
Apply FRC Team Update 4

### ISSUE THREAD

**Issue by imapcgeek** [cobracommanders/FRC-2019-Robot#18]
Control System Update: An optional NI Update Suite update (2019.1.0) has been released. This update:
o contains a new roboRIO image (v13) that repairs an issue in interfacing with the Analog Devices IMU and
Gyro boards in all languages (so, updating to this new image is needed for teams working with these
sensors)
o fixes a Driver Station issue with launching Smartdashboard and Shuffleboard automatically.
• Q&A Updates: Q101 and Q146 have been revised to reflect the revision to G4 described below. Please accept
our apologies for any confusion.

See https://firstfrc.blob.core.windows.net/frc2019/Manual/TeamUpdates/TeamUpdate04.pdf for more information

**Comment by RandyyPham** [comment]
Thank you ❤️

**Comment by pcgeek2301** [comment]
We updated our computers but we have to wait for the roboRIO

**Comment by pcgeek2301** [comment]
oops

**Comment by RandyyPham** [comment]
@hershey2314 @imapcgeek @pcgeek2301 @vyrotek @PigInATuxedo @Micalobia @DamianPX @YeeYee1318

--------------------------------------------------------
**UPDATE WPILIB IN YOUR VSCODE**
In order to deploy code to the roboRIO image v13 that came with the updated NI Suite

Here is how we did it:

- [ ] At the top-right hand corner, there is the wpilib symbol.

- [ ] Click on it, it will take you to the commands for wpi

- [ ] Then type "update" and there should be a command to check for updates for the wpi library.
<img width="379" alt="wpilibupdate" src="https://user-images.githubusercontent.com/15043276/51776310-eaaebb80-20b5-11e9-8c6b-211986568672.png">
